### ISSUE TITLE
[FEATURE] Gitpodify the project

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/SocialSlash#1]
### Description

- Add `Gitpod.yml` file in the root with the code below [official docs](https://www.gitpod.io/docs/config-start-tasks)

```yaml
tasks:
  - init: npm install 
    command: node index.js
```

- Add the Open in Gitpod button.

**For reference check out [this repo](https://github.com/Pradumnasaraf/open-API)**
